### ISSUE TITLE
v1.1 - log spam

### ISSUE THREAD

**Issue by AaronCRobinson** [XenEmpireAdmin/AnimalCollabProject#7]
Some log spam still.

Warnings:
Mod AnimalCollabProj is missing packageId in About.xml! (example: <packageId>AuthorName.ModName.Specific</packageId>)
Mod AnimalCollabProj <packageId> (EkksuHWHXenHWHCucumpearHWHThiriteHWHWhizzardHWHLindseyrieHWHWalkingHProblem164.AnimalCollabProj) is not in valid format.

Errors:
Config error in AcidBurn: Hediff with defName AcidBurn has no description!
Config error in Sting: Hediff with defName Sting has no description!
Config error in PlatypusVenom: Hediff with defName PlatypusVenom has no description!
Config error in ScorpionVenom: Hediff with defName ScorpionVenom has no description!
Config error in ToxicVenom: Hediff with defName ToxicVenom has no description!

I am not sure why it's complaining about the packageId tag but it seems like there is a bad character in there something because two of the warnings are about it. 

Let me know if i can help further.

**Comment by cucumpear** [comment]
I fixed that ages ago, but I can't push it on steam, so you're stuck with a local install. The most recent release I just drafted should not have any of these issues.
